baseURL = "https://fodor.org/"
title = "Dorin Fodor"
languagecode = "en"
author = "Dorin Fodor"
copyright = "Copyright © 2019–2020"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-123-45"
disqusShortname = "dorinfodor"
theme = "monopriv"

[params]
about = "Software engineer passionate about everything JS, Go and C++. With an interest in DevOps."
img = "img/me.jpeg"
github = "https://github.com/dorin131"
npm = "https://www.npmjs.com/~dorin131"
youtube = "https://www.youtube.com/channel/UCfFe22CVJ0e0o91QLDrwxPw/"
visualstudio = "https://marketplace.visualstudio.com/publishers/dorin131"
devto = "https://dev.to/dorin"
medium = "https://medium.com/@dorinfodor"
godoc = "https://godoc.org/github.com/dorin131/go-data-structures"
email = "******@gmail.com"
# site meta description
metadesc = "Dorin Fodor software engineer"
# site meta keywords
metakeys = "dorin, fodor, software, engineer"
# enable/disable disqus comments 
disqus = true 
# enable/disable google analytics 
analytics = false

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[permalinks]
  post = "/blog/:slug/"
  page = "/:slug/"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
